import { test } from "node:test";
import assert from "node:assert/strict";
import { auditOutputAcceptance } from "../server/lib/outputAcceptance.js";

// Real source/candidate pair retained from the first governance prospectus trial.
// The Moderate + Aggressive candidate was externally judged 100% AI and was also
// judged by the researcher as insufficiently human-textured. This fixture exists
// so that the backend must catch that failure BEFORE another paid/manual external
// detector check is worthwhile.

const source = `Introduction

Corporate debt is a central source of financing for U.S. businesses, but it is not priced solely from accounting ratios. Creditors also assess the reliability of financial reporting, the quality of oversight, the concentration of managerial authority, and the board's capacity to monitor risk. Evidence from bond and bank-loan markets shows that governance arrangements can affect credit ratings, bond yields, loan spreads, collateral requirements, covenants, and other financing terms (Anderson et al., 2004; Ashbaugh-Skaife et al., 2006; Bhojraj & Sengupta, 2003; Francis et al., 2012). The practical question is therefore not whether governance matters in the abstract, but which board-level mechanisms are credibly associated with lower borrowing costs in a contemporary U.S. setting.

This prospectus proposes an explanatory sequential mixed methods study of board independence, chief executive officer (CEO) duality, board gender diversity, board size, and audit committee independence in relation to the cost of debt among U.S.-listed manufacturing firms in the S&P 1500. The quantitative strand will estimate firm-level relationships over 2015-2024. The qualitative strand will then explain how corporate finance executives and lending professionals interpret the significant, nonsignificant, and unexpected statistical patterns. The intention is to produce an applied explanation that is empirically disciplined, theoretically coherent, and useful to decision-makers.

Background of the Problem

The scale of the U.S. corporate debt market makes small differences in borrowing cost economically important. Federal Reserve data indicate that nonfinancial corporate debt securities and loans totaled approximately $13.68 trillion in 2024, while nonfinancial corporate interest payments were approximately $639.36 billion (Board of Governors of the Federal Reserve System, n.d.-a, n.d.-b). Corporate bond issuance also reached approximately $2.0 trillion in 2024, an increase of 30.6% from the prior year (Securities Industry and Financial Markets Association [SIFMA], 2025). These figures do not establish that governance caused the observed financing burden, but they demonstrate the decision context in which firms, lenders, and boards evaluate any governance mechanism claimed to reduce credit risk or financing cost.

Creditors have reasons to examine governance because debt creates agency conflicts that differ from those of shareholders. Managers may increase operating or financial risk after debt is issued, transfer value through distributions, or use information advantages in ways that weaken creditor protection. Governance and reporting mechanisms can reduce these concerns by improving monitoring and the credibility of information available to lenders. Sengupta (1998) found that firms with higher disclosure quality incurred lower effective interest costs, while Bhojraj and Sengupta (2003) linked outside board control to higher bond ratings and lower yields. Anderson et al. (2004) further reported that board independence, board size, and fully independent audit committees were associated with lower debt costs among S&P 500 firms.

The creditor response to governance is not uniformly favorable. Klock et al. (2005) found that some antitakeover provisions reduced bondholder risk even though such provisions could weaken shareholder rights. Chava et al. (2009) similarly reported that firms with weaker takeover defenses faced higher bank-loan spreads, illustrating that creditors may value mechanisms that constrain risk shifting even when shareholders prefer greater managerial discipline. Bradley and Chen (2015) found that board independence reduced debt cost when credit conditions were strong or leverage was low, but increased it when credit conditions were poor or leverage was high. These results show that governance mechanisms can have conditional, nonlinear, or stakeholder-specific consequences rather than a single universal effect.

Board leadership and composition also provide mixed signals. Ashbaugh-Skaife et al. (2006) associated greater CEO power with lower credit ratings, and Liu and Jiraporn (2010) found that powerful CEOs were associated with lower ratings, higher bond yields, and more opaque information environments. In contrast, direct U.S. evidence on CEO duality and accounting-based debt cost remains limited. Gender-diversity studies are similarly contingent. Benjamin and Biswas (2019) found no overall relationship between female board representation and cost of debt for S&P 1500 firms, but identified a negative relationship among firms without CEO duality. Studies in other institutional settings have generally found lower debt costs when female directors are present or sufficiently represented. The magnitude depends on independence, critical mass, and market context (Garcia-Blandon et al., 2024; Karavitis et al., 2021; Pandey et al., 2020; Usman et al., 2019).

The post-2015 period also warrants focused analysis. Corporate borrowing during 2015-2024 occurred across low-rate conditions, the COVID-19 disruption, rapid policy tightening, and changing expectations concerning disclosure, risk oversight, and board accountability. Hojat and Sharifzadeh (2017) showed that U.S. firms respond heterogeneously to monetary-policy conditions, supporting the use of firm-level panel analysis and year effects rather than assuming a common financing environment. The period therefore provides substantial within-firm and across-time variation, while remaining recent enough to reflect contemporary governance and credit-market practices.

Manufacturing firms provide a coherent setting for the proposed inquiry because their financing structures commonly combine long-lived productive assets, inventories, working-capital needs, and recurring access to public or private debt. Restricting the study to manufacturing firms reduces uncontrolled variation that would arise from combining financial institutions, utilities, technology platforms, and asset-light service businesses under one model. The S&P Composite 1500 combines the S&P 500, S&P MidCap 400, and S&P SmallCap 600, covering approximately 90% of U.S. market capitalisation. It provides a defined large-, mid-, and small-cap framework for the proposed study (S&P Dow Jones Indices, 2026).

The existing evidence therefore presents a practical difficulty. Some governance mechanisms appear to reduce information risk and debt cost; others protect shareholders in ways that can increase creditor risk; and several relationships vary with leverage, credit conditions, leadership structure, or institutional context. Most prior studies examine a single governance mechanism, a single debt market, an earlier regulatory period, or a non-U.S. sample. A decision-maker cannot safely infer from that fragmented evidence that adding an independent director, separating the CEO and chair roles, increasing board diversity, enlarging the board, or restructuring the audit committee will necessarily reduce the firm's borrowing cost.

Problem Statement

U.S. nonfinancial corporations carried approximately $13.68 trillion in debt securities and loans and paid approximately $639.36 billion in interest during 2024 (Board of Governors of the Federal Reserve System, n.d.-a, n.d.-b). Prior research links board monitoring, CEO power, board composition, audit oversight, and reporting quality to bond yields, credit ratings, and bank-loan terms. The direction and strength of these relationships remain inconsistent across mechanisms and conditions, however (Anderson et al., 2004; Bradley & Chen, 2015; Francis et al., 2012; Liu & Jiraporn, 2010). The general business problem is that corporate governance investments may not produce the creditor-risk benefits assumed by firms and lenders. Corporate finance leaders of U.S.-listed manufacturing firms lack integrated, contemporary evidence concerning which board-level governance mechanisms are associated with lower accounting-based debt costs and how lenders interpret those mechanisms when pricing credit. This uncertainty can impair governance-resource allocation, debt negotiation, and credit-risk assessment.`;

const failedModerateAggressive = `Introduction

Corporate debt is a central source of financing for U.S. businesses, but it is not priced solely from accounting ratios. Creditors also assess the reliability of financial reporting, the quality of oversight, the concentration of managerial authority, and the board's capacity to monitor risk. Evidence from bond and bank-loan markets shows that governance arrangements can affect credit ratings, bond yields, loan spreads, collateral requirements, covenants, and other financing terms (Anderson et al., 2004; Ashbaugh-Skaife et al., 2006; Bhojraj & Sengupta, 2003; Francis et al., 2012). The practical question is not whether governance matters in the abstract, but which board-level mechanisms are credibly associated with lower borrowing costs in a contemporary U.S. setting.

This prospectus proposes an explanatory sequential mixed methods study of board independence, chief executive officer (CEO) duality, board gender diversity, board size, audit committee independence, and the cost of debt of U.S.-listed manufacturing firms in the S&P 1500. The quantitative strand will estimate firm-level relationships over 2015-2024. The qualitative strand will then explain how corporate finance executives and lending professionals interpret the significant, nonsignificant, and unexpected statistical patterns. The design aims to produce an explanation that is empirically grounded, theoretically coherent, and useful to decision-makers.

Background of the Problem

The scale of the U.S. corporate debt market makes small differences in borrowing cost economically important. Federal Reserve data indicate that nonfinancial corporate debt securities and loans totaled approximately $13.68 trillion in 2024. Nonfinancial corporate interest payments were approximately $639.36 billion (Board of Governors of the Federal Reserve System, n.d.-a, n.d.-b). Corporate bond issuance also reached approximately $2.0 trillion in 2024, an increase of 30.6% from the prior year (Securities Industry and Financial Markets Association [SIFMA], 2025). Firms, lenders, and boards evaluate any governance mechanism claimed to reduce credit risk or financing cost within this decision context, though the observed financing burden does not establish that governance caused it.

Debt creates agency conflicts that differ from those of shareholders. Managers may increase operating or financial risk after debt is issued, transfer value through distributions, or use information advantages in ways that weaken creditor protection. Governance and reporting mechanisms can reduce these concerns by improving monitoring and the credibility of information available to lenders. Sengupta (1998) found that firms with higher disclosure quality incurred lower effective interest costs, while Bhojraj and Sengupta (2003) linked outside board control to higher bond ratings and lower yields. Anderson et al. (2004) further reported that board independence, board size, and fully independent audit committees were associated with lower debt costs among S&P 500 firms.

The creditor response to governance is not uniformly favorable. Some antitakeover provisions reduced bondholder risk even though such provisions could weaken shareholder rights (Klock et al., 2005). Firms with weaker takeover defenses faced higher bank-loan spreads (Chava et al., 2009). Board independence reduced debt cost when credit conditions were strong or leverage was low, but increased it when credit conditions were poor or leverage was high (Bradley & Chen, 2015). Creditors may value mechanisms that constrain risk shifting even when shareholders prefer greater managerial discipline. Governance mechanisms can therefore produce conditional or stakeholder-specific consequences.

Board leadership and composition also provide mixed signals. Greater CEO power was associated with lower credit ratings (Ashbaugh-Skaife et al., 2006), and powerful CEOs were associated with lower ratings, higher bond yields, and more opaque information environments (Liu & Jiraporn, 2010). Direct U.S. evidence on CEO duality and accounting-based debt cost remains limited. Gender-diversity studies are similarly contingent. Benjamin and Biswas (2019) found no overall relationship between female board representation and cost of debt for S&P 1500 firms, but identified a negative relationship among firms without CEO duality. Studies in other institutional settings have generally found lower debt costs when female directors are present or sufficiently represented, although the magnitude depends on independence, critical mass, and market context (Garcia-Blandon et al., 2024; Karavitis et al., 2021; Pandey et al., 2020; Usman et al., 2019).

Corporate borrowing during 2015-2024 occurred across low-rate conditions, the COVID-19 disruption, rapid policy tightening, and changing expectations concerning disclosure, risk oversight, and board accountability. Hojat and Sharifzadeh (2017) showed that U.S. firms respond heterogeneously to monetary-policy conditions, supporting the use of firm-level panel analysis and year effects rather than assuming a common financing environment. The period provides substantial within-firm and across-time variation, while remaining recent enough to reflect contemporary governance and credit-market practices.

Manufacturing firms provide a coherent setting for the proposed inquiry because their financing structures commonly combine long-lived productive assets, inventories, working-capital needs, and recurring access to public or private debt. Restricting the study to manufacturing firms reduces uncontrolled variation that would arise from combining financial institutions, utilities, technology platforms, and asset-light service businesses under one model. The S&P Composite 1500 combines the S&P 500, S&P MidCap 400, and S&P SmallCap 600, covering approximately 90% of U.S. market capitalisation and providing a defined large-, mid-, and small-cap framework for the proposed study (S&P Dow Jones Indices, 2026).

Some governance mechanisms appear to reduce information risk and debt cost; others protect shareholders in ways that can increase creditor risk; and several relationships vary with leverage, credit conditions, leadership structure, or institutional context. Most prior studies examine a single governance mechanism, a single debt market, an earlier regulatory period, or a non-U.S. sample. A decision-maker cannot safely infer from that fragmented evidence that adding an independent director, separating the CEO and chair roles, increasing board diversity, enlarging the board, or restructuring the audit committee will necessarily reduce the firm's borrowing cost.

Problem Statement

U.S. nonfinancial corporations carried approximately $13.68 trillion in debt securities and loans and paid approximately $639.36 billion in interest during 2024 (Board of Governors of the Federal Reserve System, n.d.-a, n.d.-b). Prior research links board monitoring, CEO power, board composition, audit oversight, and reporting quality to bond yields, credit ratings, and bank-loan terms (Anderson et al., 2004; Bradley & Chen, 2015; Francis et al., 2012; Liu & Jiraporn, 2010). The direction and strength of these relationships are inconsistent across mechanisms and conditions. The general business problem is that corporate governance investments may not produce the creditor-risk benefits assumed by firms and lenders. Some corporate finance leaders of U.S.-listed manufacturing firms lack integrated, contemporary evidence concerning which board-level governance mechanisms are associated with lower accounting-based debt costs and how lenders interpret those mechanisms when pricing credit. This uncertainty can impair governance-resource allocation, debt negotiation, and credit-risk assessment.`;

test("the real failed Moderate + Aggressive governance output is blocked before another external detector check", () => {
  const audit = auditOutputAcceptance({
    sourceText: source,
    candidateText: failedModerateAggressive,
    styleFilters: { document_type: "prospectus", discipline: "Finance", section: "background" },
    rewriteIntensity: "moderate",
    naturalisation: "aggressive",
    planSummary: { MICRO_EDIT: 53, SPLIT_OR_MERGE: 10, SENTENCE_RESTRUCTURE: 1 },
  });

  assert.notEqual(audit.status, "pass", `failed trial unexpectedly passed with score ${audit.score}`);
  assert.equal(audit.release_gate.external_detector_check_recommended, false);
  assert.ok(
    audit.reasons.includes("machine_pattern_reduction_insufficient") ||
    audit.reasons.includes("high_machine_pattern_residual") ||
    audit.reasons.includes("source_skeleton_dependence_high") ||
    audit.reasons.includes("machine_pattern_regression"),
    `expected a machine-pattern/source-dependence reason, received: ${audit.reasons.join(", ")}`
  );
});
